version: "2"

services:
  viz:
    build: .
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "777:777"
    deploy:
      placement:
        constraints: [node.role == manager]
